ALTER TABLE `msrb`.`ISSUES` 
CHANGE COLUMN `DEFINITIONS_PAGE` `DEFINITIONS_PAGE` VARCHAR(200) NULL DEFAULT NULL ;
CHANGE COLUMN `SOURCES_AND_USES_PAGE` `SOURCES_AND_USES_PAGE` VARCHAR(200) NULL DEFAULT NULL ,
CHANGE COLUMN `DSRF_PAGE` `DSRF_PAGE` VARCHAR(100) NULL DEFAULT NULL ;
ADD COLUMN `INVESTMENTS_PAGE` VARCHAR(200) NULL DEFAULT NULL AFTER `DEFINITIONS_PAGE`;
